version: '3.8'

services:
  api:
    build: .
    container_name: fraud_detection_api
    ports:
      - "8000:8000"
    command: uvicorn src.api.app:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    restart: always

  ui:
    build: .
    container_name: fraud_detection_ui
    ports:
      - "8501:8501"
    command: streamlit run src/ui/app.py --server.address=0.0.0.0 --server.port=8501
    volumes:
      - .:/app
    depends_on:
      - api
    restart: always